name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.3.0"
          use-dotnet: false
          include-templates: true

      - name: Check Godot
        run: godot --version

      - name: Check project
        run: |
          godot --headless --path . --editor --quit

      - name: Check Android export templates
        run: |
          ls -R ~/.local/share/godot/export_templates/4.3.stable || true

      - name: Build Android
        run: |
          mkdir -p build
          godot --headless \
            --path . \
            --export-debug "Android" \
            build/LoviBanki.apk

      - name: Check APK
        run: |
          ls -lh build
          test -f build/LoviBanki.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LoviBanki-APK
          path: build/LoviBanki.apk
