name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.3.0"
          use-dotnet: false
          include-templates: true

      - name: Check project
        run: godot --headless --editor --quit

      - name: Build APK
        run: |
          mkdir -p build
          godot --headless --path . --export-release "Android" build/LoviBanki.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LoviBanki-APK
          path: build/LoviBanki.apk
